server:
  port: 8080
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      # 非空判断(只对字符串类型字段,其他类型字段依然为非NULL判断)
      select-strategy: not_empty
logging:
  level:
    com.mxc.springbootmybatisquick.mybatis.mapper: debug